// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx7NLu52eBKOW9F6O1E-XAmbWzeIKWDDc',
    appId: '1:46018152333:web:e0afa090e7e145b8aadfc4',
    messagingSenderId: '46018152333',
    projectId: 'navigation-9d108',
    authDomain: 'navigation-9d108.firebaseapp.com',
    storageBucket: 'navigation-9d108.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCdBvGtzf2g112yLDTI0y1DwrUOOFvsLQ',
    appId: '1:46018152333:android:78bd5e2f1f891fecaadfc4',
    messagingSenderId: '46018152333',
    projectId: 'navigation-9d108',
    storageBucket: 'navigation-9d108.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlN-aoMXTD9CDAMisigBm3kMpHAy85xaw',
    appId: '1:46018152333:ios:d264cfd718913ce2aadfc4',
    messagingSenderId: '46018152333',
    projectId: 'navigation-9d108',
    storageBucket: 'navigation-9d108.firebasestorage.app',
    iosClientId: '46018152333-n7sieaibuolh99cp67ail67fi3krciu5.apps.googleusercontent.com',
    iosBundleId: 'com.example.janane',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlN-aoMXTD9CDAMisigBm3kMpHAy85xaw',
    appId: '1:46018152333:ios:d264cfd718913ce2aadfc4',
    messagingSenderId: '46018152333',
    projectId: 'navigation-9d108',
    storageBucket: 'navigation-9d108.firebasestorage.app',
    iosClientId: '46018152333-n7sieaibuolh99cp67ail67fi3krciu5.apps.googleusercontent.com',
    iosBundleId: 'com.example.janane',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAx7NLu52eBKOW9F6O1E-XAmbWzeIKWDDc',
    appId: '1:46018152333:web:ad24ea40cce175ceaadfc4',
    messagingSenderId: '46018152333',
    projectId: 'navigation-9d108',
    authDomain: 'navigation-9d108.firebaseapp.com',
    storageBucket: 'navigation-9d108.firebasestorage.app',
  );
}
