name: flutter_chat_shell
description: A Flutter chat app template with GoRouter and Firebase.
publish_to: "none" # Remove this if publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.1.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Navigation
  cupertino_icons: ^1.0.8
  go_router: ^14.1.4

  # Firebase Core
  firebase_core: ^2.32.0

  # Firebase Services
  firebase_auth: ^4.8.0
  cloud_firestore: ^4.9.0
  firebase_storage: ^11.0.16       # Optional: for file uploads
  firebase_messaging: ^14.9.4     # Optional: for push notifications

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
